version: "3.8"
services:
  api:
    image: "syauqiamiq/oc-api-gateway:latest"
    ports:
      - "9111:9111"
    environment:
      - RUNNING_PORT=9111
      - DB_HOST=/run/secrets/USER_SVC_DB_HOST
      - DB_USERNAME=/run/secrets/USER_SVC_DB_USERNAME
      - DB_PASSWORD=/run/secrets/USER_SVC_DB_PASSWORD
      - DB_PORT=/run/secrets/USER_SVC_DB_PORT
      - DB_NAME=/run/secrets/USER_SVC_DB_NAME
      - MEDIA_SERVICE_URL=/run/secrets/MEDIA_SERVICE_URL
      - USER_SERVICE_URL=/run/secrets/USER_SERVICE_URL
      - COURSE_SERVICE_URL=/run/secrets/COURSE_SERVICE_URL
      - PAYMENT_SERVICE_URL=/run/secrets/PAYMENT_SERVICE_URL
      - JWT_TOKEN_SECRET=/run/secrets/JWT_TOKEN_SECRET
      - JWT_TOKEN_EXPIRED=3600
      - JWT_REFRESH_TOKEN_SECRET=/run/secrets/JWT_REFRESH_TOKEN_SECRET
      - JWT_REFRESH_TOKEN_EXPIRED=86400
      - ENV=production
    secrets:
      - USER_SVC_DB_HOST
      - USER_SVC_DB_USERNAME
      - USER_SVC_DB_PASSWORD
      - USER_SVC_DB_PORT
      - USER_SVC_DB_NAME
      - COURSE_SERVICE_URL
      - PAYMENT_SERVICE_URL
      - USER_SERVICE_URL
      - MEDIA_SERVICE_URL
      - JWT_TOKEN_SECRET
      - JWT_REFRESH_TOKEN_SECRET
    networks:
      - nginx-proxy-manager_default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
secrets:
  USER_SVC_DB_HOST:
    external: true
  USER_SVC_DB_USERNAME:
    external: true
  USER_SVC_DB_PASSWORD:
    external: true
  USER_SVC_DB_PORT:
    external: true
  USER_SVC_DB_NAME:
    external: true
  MEDIA_SERVICE_URL:
    external: true
  USER_SERVICE_URL:
    external: true
  COURSE_SERVICE_URL:
    external: true
  PAYMENT_SERVICE_URL:
    external: true
  JWT_TOKEN_SECRET:
    external: true
  JWT_REFRESH_TOKEN_SECRET:
    external: true

networks:
  nginx-proxy-manager_default:
    external: true
