name: CI/CD Deployment

on:
  push:
    branches:
      - "main"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.prod
          push: true
          tags: syauqiamiq/oc-api-gateway:latest
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Deploy
        uses: kitconcept/docker-stack-deploy@v1.0.1
        with:
          registry: "registry.hub.docker.com"
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          stack_file: "./docker-compose.yml"
          stack_name: "oc-api-gateway"
